apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: pisitindex/nextjs-argo-demo:latest
          ports:
            - containerPort: 3000
