apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
